### ISSUE TITLE
Portofolio updated with to-do-list

### ISSUE THREAD

**Issue by kazaneza** [otmanTR/Portfolio-Project#18]
### You project is good so far but we suggest adding 

- [ ] Try to fix  broken image
- [ ] Your link to the project in invalid
- [ ] Make your project DRY
